instagram:
    min_time_between_actions: 5 # in seconds
    n_likes: 150
    n_comments: 150
    n_follows: 100 # this contains n(unfollows) too!
    max_following: 7500

x:
    min_time_between_actions: 1
    n_likes: 100
    n_follows: 200
    n_comments: 100
    max_following: 5000
