# time to wait before unfollowing a user if they don't follow you back! (used in dynamic unfollow)
unfollow_gap: 7 # in days

# this is calculated for each user by n(following)/n(followers). the greater the more likely they would follow back!
accepted_follow_ratio: 1 # only users with a ratio greater than the specified value will be followed

# hashtags the user is into
hashtags:
    - "inception"
    - "einstein"
    - "interstellar"
