# time to wait before unfollowing a user if they don't follow you back! (used in dynamic unfollow)
unfollow_gap: 7 # in days

# this is calculated for each user by n(following)/n(followers). the greater the more likely they would follow back!
accepted_follow_ratio: 1 # only users with a ratio greater than the specified value will be followed

# whether to automatically mute the users the bot follows
automatic_muting: true

# whether to follow private accounts (NOTE: these can't be automatically muted)
follow_private_accounts: false

# whether to only follow or to do both following and liking
only_follow: true

# we should wait till different elements appear. this is the approximate waiting time period (higher the slower. but make sure this is greater than 5 seconds)
base_waiting_time: 6 # in seconds

# hashtags the user is into
hashtags:
    - "visionpro"
    - "mkbhd"
    - "programming"
    - "python"
    - "automation"
