accepted_follow_ratio: 2.0
automatic_muting: true
base_waiting_time: 10.0
follow_private_accounts: true
hashtags:
- visionpro
- mkbhd
- programming
- python
- automation
only_follow: true
unfollow_gap: 7.0
